# Delhi_Climate_Data_Analysis_NumPy.ipynb

In [4]:
import numpy as np


## Load the data from csv.

In [5]:
data = np.genfromtxt("/content/DailyDelhiClimateTest.csv",delimiter=",",skip_header=1,usecols=1)

In [ ]:
dates = np.genfromtxt("/content/DailyDelhiClimateTest.csv",delimiter=",",skip_header=1,usecols=0, dtype='str')

## Extracting features (columns) into NumPy arrays

In [6]:
temp = data
humidity = np.genfromtxt("/content/DailyDelhiClimateTest.csv", delimiter=",", skip_header=1, usecols=2)
wind = np.genfromtxt("/content/DailyDelhiClimateTest.csv", delimiter=",", skip_header=1, usecols=3)
pressure = np.genfromtxt("/content/DailyDelhiClimateTest.csv", delimiter=",", skip_header=1, usecols=4)

## Total Records

In [7]:
print("Total Records:", len(temp))

Total Records: 114


## Temperature Analysis

In [8]:
# Average Temperature
print("Average Temperature:",np.mean(temp))

Average Temperature: 21.713078920263158


In [9]:
# Maximum Temperature
print("Maximum Temperature:",np.max(temp))

Maximum Temperature: 34.5


In [10]:
# Minimum Temperature
print("Minimum Temperature:",np.min(temp))

Minimum Temperature: 11.0


## Weather Condition Analysis

In [22]:
# Hot Days (>30°C)
print(np.sum(temp > 30))

17


In [27]:
# Days Above Average Temperature
print("Days Above Average Temperature  :", np.mean(temp))

Days Above Average Temperature  : 21.713078920263158


## Wind Speed Analysis

In [32]:
# Average Wind Speed
print("Average Wind Speed:",np.mean(wind))

Average Wind Speed: 8.143924054535088


In [34]:
# Maximum Wind Speed
print("Maximum Wind Speed:",np.max(wind))

Maximum Wind Speed: 19.31428571


## Pressure Analysis

In [36]:
# Maximum Pressure
print("Maximum Pressure:",np.max(pressure))

Maximum Pressure: 1022.809524


In [38]:
# Average Pressure
print("Average Pressure:",np.mean(pressure))

Average Pressure: 1004.0350897017544


In [42]:
# Minimum Pressure
print("Minimum Pressure:",np.min(pressure))

Minimum Pressure: 59.0


## Correlation Analysis

In [47]:
# Temperature vs Humidity
np.corrcoef(temp,humidity)

array([[ 1.        , -0.85772623],
       [-0.85772623,  1.        ]])

In [45]:
# Temperature vs Wind Speed
np.corrcoef(temp,wind)

array([[1.        , 0.21774287],
       [0.21774287, 1.        ]])

In [48]:
# Temperature vs Pressure
np.corrcoef(temp,pressure)

array([[1.        , 0.03068192],
       [0.03068192, 1.        ]])

## Sorting Analysis

In [55]:
# Top 10 Hottest Temperatures
print(np.sort(temp)[-10:])

[31.22222222 31.375      32.         32.55555556 32.875      32.9
 33.5        34.         34.25       34.5       ]


In [56]:
# Top 10 Coldest Temperatures
print(np.sort(temp)[:10])

[11.         11.72222222 11.78947368 12.11111111 13.04166667 13.2
 13.23529412 14.57142857 14.61904762 14.65      ]
