Numpy array vs Python lists

In [ ]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c =[]
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)


3.8309011459350586


In [ ]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
import time

start = time.time()
c = a + b
print(time.time()-start)


0.36611104011535645


In [ ]:
1.88/0.03

62.666666666666664

In [ ]:
# memory  in python
a = [ i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [ ]:
# memory in numpy
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

Advanced Indexing

In [ ]:
# Normal indexing or Slicing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[1,2]

np.int64(6)

In [ ]:
# Fancy indexing
# row

a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
 # colm
a[:,[0,2,3]]

array([[14, 63, 29],
       [97, 48, 76],
       [37, 14, 63],
       [98, 92,  3],
       [46, 36, 74],
       [34, 53, 81]])

In [ ]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[14, 23, 63, 29],
       [97, 71, 48, 76],
       [37, 12, 14, 63],
       [98, 27, 92,  3],
       [46, 78, 36, 74],
       [34, 56, 53, 81]])

In [ ]:
# find all numbers greater than 50
# Bollean format
a>50

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False,  True]])

In [ ]:
# find all numbers greater than 50
a[a>50]

array([96, 56, 93, 88, 55, 83, 52, 97, 78, 61, 93, 75, 66, 63, 93])

In [ ]:
# find all even number
a[a % 2 == 0]

array([24, 96, 56, 30, 88, 52, 78,  8, 66, 26,  6])

In [ ]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([96, 56, 88, 52, 78, 66])

In [ ]:
# find all numbers not divisible by 7
a[a % 7 != 0]

array([24, 96, 93, 31, 30, 88, 55, 33, 83, 52, 97, 78, 61, 93,  8, 75,  5,
       66, 41, 26,  6, 93])

# Broadcasting

In [ ]:
# Rules
# 1. Make the two arrays have the same number of dimensions.
# • If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

# 2. Make each dimension of the two arrays the same size.
# • If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
# • If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [ ]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
a + b

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
a + b

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


array([[0, 2, 4],
       [3, 5, 7]])

In [ ]:
# more example
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
a + b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
a + b

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
a + b

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Working with matthemtical formulas

In [ ]:
# sigmoid function
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))



sigmoid(a)

array([[0.5       , 0.73105858, 0.88079708],
       [0.95257413, 0.98201379, 0.99330715],
       [0.99752738, 0.99908895, 0.99966465],
       [0.99987661, 0.9999546 , 0.9999833 ]])

In [ ]:
actual = np.arange(1,50,25)
predicted = np.arange(1,50,15)
actual


array([ 1, 26])

In [ ]:
import numpy as np

def mse(actual, predicted):
    return np.mean((actual - predicted) ** 2)

actual = np.array([10, 20, 30, 40])
predicted = np.array([12, 18, 29, 41])

print(mse(actual, predicted))

2.5


In [ ]:
# working with missing value  -> np.nan\
import numpy as np
a = np.array([1, 2, 3, 4,np.nan, 6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [ ]:
# boolean indexing

a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

# np.sort

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a


array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[95, 51, 46, 62],
       [ 4, 91, 86, 21],
       [38, 54, 17, 64],
       [35, 37,  6, 58],
       [76, 12, 89, 92],
       [30, 54, 51, 41]])

In [ ]:
np.sort(a)

array([ 9, 15, 15, 18, 20, 23, 28, 41, 71, 76, 83, 86, 87, 88, 99])

In [ ]:
np.sort(b,axis=0)

array([[ 4, 12,  6, 21],
       [30, 37, 17, 41],
       [35, 51, 46, 58],
       [38, 54, 51, 62],
       [76, 54, 86, 64],
       [95, 91, 89, 92]])

# np.append

In [ ]:
# code  1D arry
np.append(a,200)

array([ 41,  28,  86,  76,   9,  87,  23,  15,  88,  20,  83,  15,  71,
        18,  99, 200])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[95., 51., 46., 62.,  1.],
       [ 4., 91., 86., 21.,  1.],
       [38., 54., 17., 64.,  1.],
       [35., 37.,  6., 58.,  1.],
       [76., 12., 89., 92.,  1.],
       [30., 54., 51., 41.,  1.]])

# np.concatenate


In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#second method
np.hstack((c,d))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique


In [ ]:
# code
e = np.array([1,1,1,1,2,2,3,3,3,4,5,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims


In [ ]:
# code
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
# row
np.expand_dims(a,axis=0)

array([[41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99]])

In [ ]:
# colm
np.expand_dims(a,axis=1)

array([[41],
       [28],
       [86],
       [76],
       [ 9],
       [87],
       [23],
       [15],
       [88],
       [20],
       [83],
       [15],
       [71],
       [18],
       [99]])

# np.where

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
# find all index with value grater than 50
np.where(a>50)

(array([ 2,  3,  5,  8, 10, 12, 14]),)

In [ ]:
# replace all values > 50 with 0\
# np.where(condition,true,false)
np.where(a>50,0,a)

array([41, 28,  0,  0,  9,  0, 23, 15,  0, 20,  0, 15,  0, 18,  0])

In [ ]:
# replace all values with even
np.where(a % 2 == 0,0,a)

array([41,  0,  0,  0,  9, 87, 23, 15,  0,  0, 83, 15, 71,  0, 99])

# np.argmax

In [ ]:
# code
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
# maximum no
np.argmax(a)

np.int64(14)

In [ ]:
b

array([[95, 51, 46, 62],
       [ 4, 91, 86, 21],
       [38, 54, 17, 64],
       [35, 37,  6, 58],
       [76, 12, 89, 92],
       [30, 54, 51, 41]])

In [ ]:
np.argmax(b,axis = 1)

array([0, 1, 3, 3, 3, 1])

In [ ]:
# minimum no
np.argmin(a)

np.int64(4)

# np.cumsum = cumulative sum

In [ ]:
a


array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
# vaues + + + +
np.cumsum(a)

array([ 41,  69, 155, 231, 240, 327, 350, 365, 453, 473, 556, 571, 642,
       660, 759])

In [ ]:
b

array([[95, 51, 46, 62],
       [ 4, 91, 86, 21],
       [38, 54, 17, 64],
       [35, 37,  6, 58],
       [76, 12, 89, 92],
       [30, 54, 51, 41]])

In [ ]:
# 2D
np.cumsum(b,axis=1)

array([[ 95, 146, 192, 254],
       [  4,  95, 181, 202],
       [ 38,  92, 109, 173],
       [ 35,  72,  78, 136],
       [ 76,  88, 177, 269],
       [ 30,  84, 135, 176]])

# cumprod  = multiplication

In [ ]:
np.cumprod(a)

array([                  41,                 1148,                98728,
                    7503328,             67529952,           5875105824,
               135127433952,        2026911509280,      178368212816640,
           3567364256332800,   296091233275622400,  4441368499134336000,
        1742514185475478528, -5528232808860489728,  6107274134098065408])

# np.percentile

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
# 50 % array values
np.percentile(a,50)
#like
np.median(a)

np.float64(41.0)

# np.histogram

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

# np.corrcoef = corelation and coeficcent

In [ ]:
import numpy as np


In [ ]:

salary = np.array([2000,4000,35000,65000])
experience = np.array([1,3,2,4])

In [ ]:

np.corrcoef(salary,experience)


array([[1.        , 0.68488815],
       [0.68488815, 1.        ]])

# np.isin

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
a[np.isin(a,[10,20,30,40,50,25,70,80,90])]

array([20])

# np.flip

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
np.flip(a)

array([99, 18, 71, 15, 83, 20, 88, 15, 23, 87,  9, 76, 86, 28, 41])

In [ ]:
b

array([[95, 51, 46, 62],
       [ 4, 91, 86, 21],
       [38, 54, 17, 64],
       [35, 37,  6, 58],
       [76, 12, 89, 92],
       [30, 54, 51, 41]])

In [ ]:
np.flip(b,axis=1)

array([[62, 46, 51, 95],
       [21, 86, 91,  4],
       [64, 17, 54, 38],
       [58,  6, 37, 35],
       [92, 89, 12, 76],
       [41, 51, 54, 30]])

# np.put

In [ ]:
a

array([41, 28, 86, 76,  9, 87, 23, 15, 88, 20, 83, 15, 71, 18, 99])

In [ ]:
np.put(a,[0,1],[110,290])
a

array([110, 290,  86,  76,   9,  87,  23,  15,  88,  20,  83,  15,  71,
        18,  99])

# np.delete

In [ ]:
a

array([110, 290,  86,  76,   9,  87,  23,  15,  88,  20,  83,  15,  71,
        18,  99])

In [ ]:
np.delete(a,[0,3,5])

array([290,  86,   9,  23,  15,  88,  20,  83,  15,  71,  18,  99])

# set function
 * np.union1d
 * np.intersect1d
 * np.setdiff1d
 * np.setxor1d
 * np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,7,8,9])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [ ]:
np.intersect1d(m,n)

array([3, 4])

In [ ]:
# in m but not n
np.setdiff1d(m,n)

array([1, 2, 5])

In [ ]:
# only comman value
np.setxor1d(m,n)

array([1, 2, 5, 7, 8, 9])

In [ ]:
# item searching
np.in1d(m,1)

/tmp/ipykernel_830/1689317911.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip

In [ ]:
a

array([110, 290,  86,  76,   9,  87,  23,  15,  88,  20,  83,  15,  71,
        18,  99])

In [ ]:
# set value in range 25 - 75
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 75, 25, 25, 75, 25, 75, 25, 71, 25, 75])