In [ ]:
# np. array
import numpy as np
a = np.array ([1, 2, 3])
print(a)


[1 2 3]


In [ ]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#dtype
a = np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [ ]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#np reshape
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.06586742, 0.66571804, 0.76692303, 0.49242921],
       [0.8665823 , 0.8273977 , 0.55399348, 0.36373295],
       [0.29614507, 0.68104868, 0.41899293, 0.78352293]])

In [ ]:
#np.linspace  = linearly seprable for given range
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Array Attributes



In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#ndim
a2.ndim

2

In [ ]:
#shape
print(a2.shape)
a1


(3, 4)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#itemsize  #bit wise
a1.itemsize


8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [ ]:
#astype = #user can change type
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

##Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Sacaler Operation
# arithmetic
a1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# realtional
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a2 * a1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

##Array Functions


In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[37., 78., 62.],
       [81., 70.,  4.],
       [62., 72., 99.]])

In [ ]:
# max/min/sum/prod
# 0-> col and 1-> row
np.max(a1,axis=1)


array([78., 81., 99.])

In [ ]:
# mean/median/std/var
np.var(a1)


np.float64(681.5061728395062)

In [ ]:
# trignometric funstion
np.sin(a1)

array([[-0.64353813,  0.51397846, -0.7391807 ],
       [-0.62988799,  0.77389068, -0.7568025 ],
       [-0.7391807 ,  0.25382336, -0.99920683]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
#log and exponents
np.exp(a1)

array([[1.17191424e+16, 7.49841700e+33, 8.43835667e+26],
       [1.50609731e+35, 2.51543867e+30, 5.45981500e+01],
       [8.43835667e+26, 1.85867175e+31, 9.88903032e+42]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[40., 76., 28.],
       [78., 92., 75.]])

## Indexing and Slicing


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a2[1,3]

np.int64(7)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1,0]

np.int64(6)

# Slicing


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2 to 9 and which distance
a1[2:9:3]

array([2, 5, 8])

In [ ]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# find only second colm
# : = all row / all colm
a2[:,2]

array([ 2,  6, 10])

In [ ]:
# middle
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# side element
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]


array([4, 7])

In [ ]:
a2[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

Slicing 3D array

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

##Iterating


In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [ ]:
# reshape
a2.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# transpose
# a2
np.transpose(a2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# Ravel = one D array
a2
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [ ]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Spliting

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Horizontical spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Vertical spliting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Important NumPy Functions

In [ ]:
# Replace values greater than 50 with 0
a = np.random.randint(1,100,30)
print(a)
np.where(a>50,0,a)

[43 64 16 14 39 61 45 94 48 38 81 88  5 74  2 14  5 36 90 51 82 62  2 12
 60 60 56 55 25 93]


array([43,  0, 16, 14, 39,  0, 45,  0, 48, 38,  0,  0,  5,  0,  2, 14,  5,
       36,  0,  0,  0,  0,  2, 12,  0,  0,  0,  0, 25,  0])

In [ ]:
# Find index of maximum and minimum values using argmax() and argmin().
np.argmax(a),np.argmin(a)


(np.int64(7), np.int64(14))

In [ ]:
# Find unique values from an array.
a = np.array([1,1,1,2,2,3,3,4,4,4,4,5,5])
np.unique(a)

array([1, 2, 3, 4, 5])

In [ ]:
# Reverse an array using flip().
np.flip(a)

array([5, 5, 4, 4, 4, 4, 3, 3, 2, 2, 1, 1, 1])