## NumPy Practice Exercises


# Array Creation

In [1]:
# Create an array from 1 to 10.
import numpy as np
a = np.arange(1,11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
# Create a 3×3 matrix using arange() and reshape().
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Create a 5×5 identity matrix
c = np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [10]:
# Find shape, size and ndim of a matrix
a = np.arange(20).reshape(4,5)
a.shape, a.size, a.ndim

((4, 5), 20, 2)

In [5]:
# Find dtype and itemsize of an array.
a.dtype, a.itemsize

(dtype('int64'), 8)

In [11]:
# Convert integer array into float using astype().
a.astype(float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

# Array Operations & Functions

In [12]:
# Square every element of an array.
np.square(a)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [13]:
# Multiply two arrays element-wise.
a1 = np.arange(1,10)
b1 = np.arange(11,20)
a1 * b1


array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [22]:
# Find maximum value row-wise.
a3 = np.arange(1,10).reshape(3,3)
np.max(a3,axis=1)

array([3, 6, 9])

In [24]:
# Find mean, median and variance.
np.min(a1), np.mean(a1), np.var(a1)

(np.int64(1), np.float64(5.0), np.float64(6.666666666666667))

# Indexing & Slicing

In [77]:
a = np.arange(10)
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Extract the 3rd element from a 1D array.
a[3]

np.int64(3)

In [40]:
# Extract the 2nd row from a matrix.
b[1,:]

array([4, 5, 6])

In [ ]:
# Extract the last column from a matrix.

In [60]:
b[:,-1]

array([3, 6, 9])

In [80]:
# Extract middle elements from a matrix using slicing.
c = np.arange(1,17).reshape(4,4)
c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
c[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

# 3D Arrays

In [83]:
# Create a 3D array.
a = np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [87]:
# Access element at [1,1,0].
a[1,1,0]

np.int64(17)

In [84]:
# Extract first layer of a 3D array.
a[0,:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Reshaping & Iteration

In [88]:
# Convert a 1D array into a 3×4 matrix.
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
# Transpose a matrix.
a = np.arange(25)
a.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
#Convert matrix into 1D using ravel()
print(b)

np.ravel(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Stacking & Splitting




In [105]:
a = np.arange(1,25).reshape(6,4)
b = np.arange(26,50).reshape(6,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]


In [108]:
# Perform horizontal stacking.
np.hstack((a,b))

array([[ 1,  2,  3,  4, 26, 27, 28, 29],
       [ 5,  6,  7,  8, 30, 31, 32, 33],
       [ 9, 10, 11, 12, 34, 35, 36, 37],
       [13, 14, 15, 16, 38, 39, 40, 41],
       [17, 18, 19, 20, 42, 43, 44, 45],
       [21, 22, 23, 24, 46, 47, 48, 49]])

In [109]:
# Perform vertical stacking.
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [114]:
# Split a matrix vertically.
np.vsplit(a,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

# Advanced Indexing

In [116]:
# Select rows 0, 2 and 4 using Fancy Indexing.
a[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [123]:
# Extract all values greater than 20.
a[a>20]

array([21, 22, 23, 24])

In [124]:
# Extract all even numbers.
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

#
Broadcasting


In [ ]:
# Rules
# 1. Make the two arrays have the same number of dimensions.
# • If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

# 2. Make each dimension of the two arrays the same size.
# • If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
# • If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [137]:
# Add two arrays having same shape.
a = a = np.arange(1,13).reshape(3,4)
b = np.arange(14,26).reshape(3,4)
print(a)
print(b)

a + b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


array([[15, 17, 19, 21],
       [23, 25, 27, 29],
       [31, 33, 35, 37]])

In [136]:
# What is the output of the following code
# True Because
a = np.arange(12).reshape(4,3)
b = np.arange(3)

a + b



array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])